Support for the conan package manager
DLR-SC/tixi pull request #214
Opened 2022-08-29 10:44 UTC by rainman110

This PR adds support for the conan package manager.

The conanfile can be used to install the thirdparty dependencies and to create a tixi conan package.

# Using conan to install dependencies # 

The build process is slightly changed, by using `conan install` before calling cmake.

    mkdir build && cd build
    conan install .. -o shared=True
    cmake ..
    make

The argument `shared` specifies, whether tixi is built as a shared library or not.

# Create the conan package # 

Simply call

    conan create .

from the source directory.

# Adaptations to the current code # 
 - `make_tixi_matlab.py`: Allows to create in-source builds
 - `CMakeLists.txt`: Actually not required, but automatically loads the conan config, if created.
 - `FindCURL.cmake` and `cmake/tixi-config.cmake.in`: Our FindCURL module used different target names incompatible to the official targets (https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindCURL.cmake#L26) and the conan targets. Hence, a renaming was required.

## Note ##
A pull request to the conan package index to add tixi is ongoing:
https://github.com/conan-io/conan-center-index/pull/12610

The package recipe is slightly changed, since it needs to pull the sources from github first.

2022-08-29 11:05 UTC, joergbrech requested changes
Very nice! Thanks a lot! 

I have two follow-up questions:
 - What do you mean by the CMakeLists.txts is not really used anymore?
 - I would like to have the package creation *(including package test)* in CI. But I suppose I could take over and take care of it. Just let me know.

2022-08-29 12:50 UTC, rainman110 commented
> What do you mean by the CMakeLists.txts is not really used anymore?

No, you misunderstood me ;). The changes in CMakeLists.txt are not necesarrily required but helpful.

> I would like to have the package creation (including package test) in CI. But I suppose I could take over and take care of it. Just let me know.

Having something in the CI would be awesome, but I did not wanted to mix things here. Also, the CI does not seem to be running right now (at least not in this branch and PR).

2022-08-29 14:16 UTC, joergbrech commented
> No, you misunderstood me ;). The changes in CMakeLists.txt are not necesarrily required but helpful.

Ok, that makes more sense :)

> Having something in the CI would be awesome, but I did not wanted to mix things here.

Why would this be mixing things? It would be just an additional step calling `conan create` to test the package creation, which makes sense if we want to have the conanfile as part of this repo. No need to artifact the results or upload anything to a package registry if tixi3 is available on conan center.

> Also, the CI does not seem to be running right now (at least not in this branch and PR)

💩 I will investigate...

2022-08-29 14:18 UTC, rainman110 commented
I thought you wanted a separate build job. Okay, adding simply conan create . is easy. However, this will duplicate the compile time of the job since it will recompile everything.

2022-08-29 14:25 UTC, joergbrech commented
> I thought you wanted to have a separate build job. Okay, adding simply conan create . is easy. However, this will duplicate the compile time of the job since it will recompile everything.

True. I suppose it would suffice to run only on `master` or on nightly builds.

2022-08-30 20:44 UTC, rainman110 commented
@joergbrech I backported the changes from the conancenter tixi package and added a conan job for linux . Do you also want to test the packaging also in windows?

2022-08-30 21:33 UTC, joergbrech commented
No, this is great! Thanks a lot!

2022-09-05 08:52 UTC, merged